name: Documentation CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  validate:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: 3.9
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Validate documentation structure
      run: |
        # Check that required directories exist
        test -d documentation/
        test -d resourcetype/
        test -d scripts/
        
        # Count documentation files
        echo "Documentation files: $(find documentation/ -name '*.md' | wc -l)"
        echo "Resource type files: $(find resourcetype/ -name '*.md' | wc -l)"
        
        # Check main files exist
        test -f README.md
        test -f requirements.txt
        test -f CONTRIBUTING.md
        test -f LICENSE
    
    - name: Check Python scripts syntax
      run: |
        python -m py_compile scripts/*.py
    
    - name: Lint Python scripts
      run: |
        pip install flake8
        flake8 scripts/ --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 scripts/ --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
